export const CATEGORIES = [
  {
    slug: 'writing',
    icon: 'PenLine',
    sortOrder: 1,
    translations: {
      en: { name: 'Writing', description: 'AI tools for content creation, copywriting, and text generation' },
      ar: { name: 'الكتابة', description: 'أدوات الذكاء الاصطناعي لإنشاء المحتوى والكتابة وتوليد النصوص' },
      es: { name: 'Escritura', description: 'Herramientas de IA para creación de contenido y redacción' },
      fr: { name: 'Rédaction', description: 'Outils IA pour la création de contenu et la rédaction' },
      pt: { name: 'Escrita', description: 'Ferramentas de IA para criação de conteúdo e redação' },
      de: { name: 'Schreiben', description: 'KI-Tools für Content-Erstellung und Texterstellung' },
      zh: { name: '写作', description: 'AI写作、内容创作和文本生成工具' },
      hi: { name: 'लेखन', description: 'सामग्री निर्माण और लेखन के लिए AI उपकरण' },
      ja: { name: 'ライティング', description: 'コンテンツ作成・文章生成AIツール' },
      ru: { name: 'Написание', description: 'ИИ-инструменты для создания контента и написания текстов' },
    },
  },
  {
    slug: 'image',
    icon: 'Image',
    sortOrder: 2,
    translations: {
      en: { name: 'Image Generation', description: 'AI tools for generating, editing, and enhancing images' },
      ar: { name: 'توليد الصور', description: 'أدوات الذكاء الاصطناعي لتوليد الصور وتحريرها وتحسينها' },
      es: { name: 'Generación de Imágenes', description: 'Herramientas de IA para generar y editar imágenes' },
      fr: { name: 'Génération d\'Images', description: 'Outils IA pour générer et éditer des images' },
      pt: { name: 'Geração de Imagens', description: 'Ferramentas de IA para gerar e editar imagens' },
      de: { name: 'Bildgenerierung', description: 'KI-Tools für Bildgenerierung und -bearbeitung' },
      zh: { name: '图像生成', description: 'AI图像生成、编辑和增强工具' },
      hi: { name: 'छवि निर्माण', description: 'छवि बनाने और संपादित करने के लिए AI उपकरण' },
      ja: { name: '画像生成', description: '画像生成・編集AIツール' },
      ru: { name: 'Генерация Изображений', description: 'ИИ-инструменты для генерации и редактирования изображений' },
    },
  },
  {
    slug: 'video',
    icon: 'Video',
    sortOrder: 3,
    translations: {
      en: { name: 'Video', description: 'AI tools for video creation, editing, and generation' },
      ar: { name: 'الفيديو', description: 'أدوات الذكاء الاصطناعي لإنشاء الفيديو وتحريره وتوليده' },
      es: { name: 'Video', description: 'Herramientas de IA para creación y edición de video' },
      fr: { name: 'Vidéo', description: 'Outils IA pour la création et l\'édition vidéo' },
      pt: { name: 'Vídeo', description: 'Ferramentas de IA para criação e edição de vídeo' },
      de: { name: 'Video', description: 'KI-Tools für Videoerstellung und -bearbeitung' },
      zh: { name: '视频', description: 'AI视频创作、编辑和生成工具' },
      hi: { name: 'वीडियो', description: 'वीडियो बनाने के लिए AI उपकरण' },
      ja: { name: '動画', description: '動画制作・編集AIツール' },
      ru: { name: 'Видео', description: 'ИИ-инструменты для создания и редактирования видео' },
    },
  },
  {
    slug: 'code',
    icon: 'Code2',
    sortOrder: 4,
    translations: {
      en: { name: 'Code & Dev', description: 'AI coding assistants, code generators, and developer tools' },
      ar: { name: 'البرمجة والتطوير', description: 'مساعدو الذكاء الاصطناعي للبرمجة وأدوات المطورين' },
      es: { name: 'Código y Dev', description: 'Asistentes de codificación IA y herramientas de desarrollo' },
      fr: { name: 'Code & Dev', description: 'Assistants de codage IA et outils de développement' },
      pt: { name: 'Código & Dev', description: 'Assistentes de codificação IA e ferramentas de desenvolvimento' },
      de: { name: 'Code & Dev', description: 'KI-Coding-Assistenten und Entwickler-Tools' },
      zh: { name: '代码与开发', description: 'AI编程助手和开发者工具' },
      hi: { name: 'कोड और डेव', description: 'AI कोडिंग सहायक और डेवलपर टूल' },
      ja: { name: 'コード＆開発', description: 'AIコーディングアシスタントと開発ツール' },
      ru: { name: 'Код и Разработка', description: 'ИИ-ассистенты для кодирования и инструменты разработчика' },
    },
  },
  {
    slug: 'audio',
    icon: 'Mic',
    sortOrder: 5,
    translations: {
      en: { name: 'Audio', description: 'AI tools for music, voice, speech, and sound generation' },
      ar: { name: 'الصوت', description: 'أدوات الذكاء الاصطناعي للموسيقى والصوت والكلام' },
      es: { name: 'Audio', description: 'Herramientas de IA para música, voz y sonido' },
      fr: { name: 'Audio', description: 'Outils IA pour la musique, la voix et le son' },
      pt: { name: 'Áudio', description: 'Ferramentas de IA para música, voz e som' },
      de: { name: 'Audio', description: 'KI-Tools für Musik, Stimme und Sound' },
      zh: { name: '音频', description: 'AI音乐、语音和音效生成工具' },
      hi: { name: 'ऑडियो', description: 'संगीत और आवाज़ के लिए AI उपकरण' },
      ja: { name: 'オーディオ', description: '音楽・音声AIツール' },
      ru: { name: 'Аудио', description: 'ИИ-инструменты для музыки, голоса и звука' },
    },
  },
  {
    slug: 'business',
    icon: 'Briefcase',
    sortOrder: 6,
    translations: {
      en: { name: 'Business', description: 'AI tools for productivity, automation, and business workflows' },
      ar: { name: 'الأعمال', description: 'أدوات الذكاء الاصطناعي للإنتاجية والأتمتة وسير عمل الأعمال' },
      es: { name: 'Negocios', description: 'Herramientas de IA para productividad y automatización' },
      fr: { name: 'Business', description: 'Outils IA pour la productivité et l\'automatisation' },
      pt: { name: 'Negócios', description: 'Ferramentas de IA para produtividade e automação' },
      de: { name: 'Business', description: 'KI-Tools für Produktivität und Automatisierung' },
      zh: { name: '商业', description: 'AI生产力和业务自动化工具' },
      hi: { name: 'व्यापार', description: 'उत्पादकता और स्वचालन के लिए AI उपकरण' },
      ja: { name: 'ビジネス', description: '生産性・業務自動化AIツール' },
      ru: { name: 'Бизнес', description: 'ИИ-инструменты для продуктивности и автоматизации' },
    },
  },
  {
    slug: 'research',
    icon: 'Search',
    sortOrder: 7,
    translations: {
      en: { name: 'Research', description: 'AI tools for research, analysis, and knowledge discovery' },
      ar: { name: 'البحث', description: 'أدوات الذكاء الاصطناعي للبحث والتحليل واكتشاف المعرفة' },
      es: { name: 'Investigación', description: 'Herramientas de IA para investigación y análisis' },
      fr: { name: 'Recherche', description: 'Outils IA pour la recherche et l\'analyse' },
      pt: { name: 'Pesquisa', description: 'Ferramentas de IA para pesquisa e análise' },
      de: { name: 'Forschung', description: 'KI-Tools für Forschung und Analyse' },
      zh: { name: '研究', description: 'AI研究和分析工具' },
      hi: { name: 'अनुसंधान', description: 'अनुसंधान के लिए AI उपकरण' },
      ja: { name: 'リサーチ', description: '研究・分析AIツール' },
      ru: { name: 'Исследования', description: 'ИИ-инструменты для исследований и анализа' },
    },
  },
  {
    slug: 'education',
    icon: 'GraduationCap',
    sortOrder: 8,
    translations: {
      en: { name: 'Education', description: 'AI tools for learning, tutoring, and skill development' },
      ar: { name: 'التعليم', description: 'أدوات الذكاء الاصطناعي للتعلم والتدريس وتطوير المهارات' },
      es: { name: 'Educación', description: 'Herramientas de IA para aprendizaje y desarrollo de habilidades' },
      fr: { name: 'Éducation', description: 'Outils IA pour l\'apprentissage et le tutorat' },
      pt: { name: 'Educação', description: 'Ferramentas de IA para aprendizado e tutoria' },
      de: { name: 'Bildung', description: 'KI-Tools für Lernen und Kompetenzentwicklung' },
      zh: { name: '教育', description: 'AI学习和教育工具' },
      hi: { name: 'शिक्षा', description: 'सीखने के लिए AI उपकरण' },
      ja: { name: '教育', description: '学習・チュータリングAIツール' },
      ru: { name: 'Образование', description: 'ИИ-инструменты для обучения и развития навыков' },
    },
  },
  {
    slug: 'marketing',
    icon: 'Megaphone',
    sortOrder: 9,
    translations: {
      en: { name: 'Marketing', description: 'AI tools for marketing, SEO, social media, and advertising' },
      ar: { name: 'التسويق', description: 'أدوات الذكاء الاصطناعي للتسويق وتحسين محركات البحث ووسائل التواصل الاجتماعي' },
      es: { name: 'Marketing', description: 'Herramientas de IA para marketing, SEO y redes sociales' },
      fr: { name: 'Marketing', description: 'Outils IA pour le marketing, le SEO et les réseaux sociaux' },
      pt: { name: 'Marketing', description: 'Ferramentas de IA para marketing, SEO e redes sociais' },
      de: { name: 'Marketing', description: 'KI-Tools für Marketing, SEO und Social Media' },
      zh: { name: '营销', description: 'AI营销、SEO和社交媒体工具' },
      hi: { name: 'मार्केटिंग', description: 'मार्केटिंग के लिए AI उपकरण' },
      ja: { name: 'マーケティング', description: 'マーケティング・SEO AIツール' },
      ru: { name: 'Маркетинг', description: 'ИИ-инструменты для маркетинга, SEO и социальных сетей' },
    },
  },
  {
    slug: 'other',
    icon: 'Sparkles',
    sortOrder: 10,
    translations: {
      en: { name: 'Other', description: 'Other AI tools that don\'t fit into specific categories' },
      ar: { name: 'أخرى', description: 'أدوات الذكاء الاصطناعي الأخرى التي لا تندرج ضمن فئات محددة' },
      es: { name: 'Otros', description: 'Otras herramientas de IA que no encajan en categorías específicas' },
      fr: { name: 'Autres', description: 'Autres outils IA ne rentrant pas dans des catégories spécifiques' },
      pt: { name: 'Outros', description: 'Outras ferramentas de IA que não se encaixam em categorias específicas' },
      de: { name: 'Sonstiges', description: 'Andere KI-Tools, die nicht in spezifische Kategorien passen' },
      zh: { name: '其他', description: '不属于特定类别的其他AI工具' },
      hi: { name: 'अन्य', description: 'अन्य AI उपकरण' },
      ja: { name: 'その他', description: '特定のカテゴリに当てはまらないその他のAIツール' },
      ru: { name: 'Другое', description: 'Другие ИИ-инструменты, не входящие в конкретные категории' },
    },
  },
];
